plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version "$springVersion"
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web:$springVersion"
    implementation "org.springframework.boot:spring-boot-starter-cache:$springVersion"
    compileOnly "org.springframework.boot:spring-boot-devtools:$springVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-test:$springVersion"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.0.3'
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    testLogging {
        events 'passed', 'skipped', 'failed'
        exceptionFormat 'full'
        showCauses true
    }
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}
